sudo: 9000
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '4'
  - iojs-v3
  - iojs-v2
  - iojs-v1
  - '0.12'
  - '0.11'
  - '0.10'
before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash
  - npm i -g npm@^2.0.0
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
  - sudo apt-get update
  - sudo apt-get install tree
before_script:
  - npm prune
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
after_failure:
  - tree .
after_success:
  - npm run coverage
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
