sudo: 9000
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '5'
  - '4'
  - iojs-v3
  - iojs-v2
  - iojs-v1
  - '0.12'
  - '0.11'
  - '0.10'
before_install:
  - curl -s https://raw.githubusercontent.com/lovell/sharp/master/preinstall.sh | sudo bash
  - npm i -g npm@^2.0.0
  - sudo apt-get update
  - sudo apt-get install tree
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  CXX=g++-4.8
before_script:
  - npm prune
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
after_failure:
  - tree . -L 4
after_success:
  - npm run coverage
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
